server:
  port: 8082

spring:
  application:
    name: rpc-example-consumer
  profiles:
    active: dev

# RPC 配置
rpc:
  # 关键配置：指定为客户端模式
  mode: client

  # 序列化配置
  serialize:
    type: json  # 可选值: json, protobuf

  # 客户端配置
  client:
    # 超时配置
    timeout: 3000                  # 通用超时时间(毫秒)
    connect-timeout: 5000          # 连接超时(毫秒)
    request-timeout: 300000             # 请求超时(秒)
    
    # 连接模式配置
    connection-mode: eager         # 连接模式: EAGER(立即连接), LAZY(按需连接)

    maxRetries: 5                       # 最大重试次数
    # 重试配置
    retry:
      enable: true                 # 是否启用重试
      maxRetries: 5                       # 最大重试次数
      interval: 1000               # 重试间隔(毫秒)
      only-idempotent: true        # 只重试幂等操作
      # 指数退避策略配置
      backoff:
        multiplier: 2.0            # 退避乘数
        max: 30000                 # 最大退避时间(毫秒)
        jitter: true               # 是否添加随机抖动
        min: 500                   # 最小重试间隔(毫秒)
    
    # 熔断器配置
    circuit-breaker:
      enable: true                 # 是否启用熔断器
      threshold: 5                 # 错误阈值
      timeout: 30000               # 熔断时间(毫秒)
    
    # 心跳配置
    heartbeat:
      interval: 30                 # 心跳间隔(秒)
      timeout: 5                   # 心跳超时(秒)
    
    # 负载均衡配置
    load-balance:
      type: random             # 负载均衡策略: random, roundrobin, leastactive, consistenthash,weighted
    
    # 服务版本与分组配置
    service:
      version: 1.0.0               # 服务版本
      group: default               # 服务分组
    
    # 接口特定配置 (可选)
    interfaces:
      com.weihua.rpc.example.api.OrderService:
        request-timeout: 10        # 特定接口的请求超时(秒)
        retry-max: 3               # 特定接口的最大重试次数

  # 注册中心配置
  discovery:
    type: consul                   # 注册中心类型: consul, zookeeper, local
    address: 127.0.0.1:8500        # 注册中心地址
    connect-timeout: 5000          # 连接超时(毫秒)
    timeout: 3000                  # 请求超时(毫秒)
    retry-times: 3                 # 重试次数

# 日志配置
logging:
  level:
    com.weihua.rpc: info           # 框架日志级别
    org.springframework.boot.autoconfigure.condition: info  # 条件评估日志(调试时开启)
    root: warn