server:
  port: 8082

spring:
  application:
    name: rpc-example-consumer
  profiles:
    active: dev

# RPC 配置
rpc:
  mode: client

  serialize:
    type: json  # 可选值: json, protobuf

  client:
    # 超时配置
    timeout: 3s                    # 通用超时时间
    connect-timeout: 5s            # 连接超时
    request-timeout: 5m            # 请求超时
    
    # 连接模式配置
    connection-mode: eager         # 连接模式: EAGER(立即连接), LAZY(按需连接)
    
    # 重试配置
    retry:
      enable: true                 # 是否启用重试
      max-retries: 5               # 最大重试次数
      interval: 1s                 # 重试间隔
      only-idempotent: true        # 只重试幂等操作
      # 指数退避策略配置
      backoff:
        multiplier: 2.0            # 退避乘数
        max: 30s                   # 最大退避时间
        jitter: true               # 是否添加随机抖动
        min: 500ms                 # 最小重试间隔
    
    # 熔断器配置
    circuit-breaker:
      enable: true                 # 是否启用熔断器
      failures: 5                  # 错误阈值
      reset-timeout: 30s           # 熔断重置时间
    
    # 心跳配置 (优化心跳间隔)
    heartbeat:
      interval: 8s                 # 心跳间隔 (从30s优化到8s)
      timeout: 5s                  # 心跳超时
      failure-threshold: 3         # 连续失败次数阈值
    
    # 健康检查配置 (新增)
    health-check:
      initial-delay: 5s            # 初始延迟
      interval: 12s                # 检查间隔
      max-per-run: 50              # 单次最大检查数量
      
    # 连接管理配置 (新增)
    connection:
      idle-timeout: 10m            # 闲置连接超时时间
      idle-check-interval: 60s     # 闲置连接检查间隔
      grace-period: 30s            # 服务移除宽限期
    
    # 负载均衡配置
    load-balance:
      type: random                 # 负载均衡策略
    
    # 服务版本与分组配置
    service:
      version: 1.0.0               # 服务版本
      group: default               # 服务分组

  # 注册中心配置
  discovery:
    type: consul                   # 注册中心类型: consul, zookeeper, local
    address: 127.0.0.1:8500        # 注册中心地址
    connect-timeout: 5s            # 连接超时
    timeout: 3s                    # 请求超时
    retry-times: 3                 # 重试次数
    # 服务发现同步配置 (新增)
    sync-interval: 30s             # 服务发现同步间隔
    # 故障保护配置 (新增)
    fault-tolerance:
      enabled: true                # 启用注册中心故障保护
      mode: keep-last-known        # 故障模式: keep-last-known, fallback-to-local

# 日志配置
logging:
  level:
    com.weihua.rpc: info           # 框架日志级别
    root: warn