server:
  port: 8082

spring:
  application:
    name: rpc-example-consumer
  profiles:
    active: dev

# RPC 配置
rpc:
  # 关键配置：指定为客户端模式
  mode: client
  
  # 客户端配置
  client:
    # 超时配置
    timeout: 3000                  # 通用超时时间(毫秒)
    connect-timeout: 5000          # 连接超时(毫秒)
    request-timeout: 5             # 请求超时(秒)
    
    # 连接池配置
    connections:
      max: 4                       # 每个地址最大连接数
      init: 1                      # 初始连接数
    
    # 重试配置
    retry-enable: true             # 是否启用重试
    retries: 2                     # 最大重试次数
    retry-interval: 1000           # 重试间隔(毫秒)
    retry-only-idempotent: true    # 只重试幂等操作
    
    # 熔断器配置
    circuit-breaker:
      enable: true                 # 是否启用熔断器
      threshold: 5                 # 错误阈值
      timeout: 30000               # 熔断时间(毫秒)
    
    # 心跳配置
    heartbeat:
      interval: 30                 # 心跳间隔(秒)
      timeout: 5                   # 心跳超时(秒)
    
    # 负载均衡配置
    load-balance:
      type: random                 # 负载均衡策略: random, roundrobin, leastactive, consistenthash
    
    # 服务版本与分组配置
    service:
      version: 1.0.0               # 服务版本
      group: default               # 服务分组
    
    # 接口特定配置 (可选)
    interfaces:
      com.weihua.rpc.example.api.OrderService:
        request-timeout: 10        # 特定接口的请求超时(秒)
        retry-max: 3               # 特定接口的最大重试次数

  # 注册中心配置
  discovery:
    type: consul                   # 注册中心类型: consul, zookeeper, local
    address: 127.0.0.1:8500        # 注册中心地址
    connect-timeout: 5000          # 连接超时(毫秒)
    timeout: 3000                  # 请求超时(毫秒)
    retry-times: 3                 # 重试次数

# 日志配置
logging:
  level:
    com.weihua.rpc: info           # 框架日志级别
    org.springframework.boot.autoconfigure.condition: DEBUG  # 条件评估日志(调试时开启)
    root: warn