server:
  port: 8081

spring:
  application:
    name: rpc-example-provider

# RPC 配置
rpc:
  mode: server  # 新增：指定模式为服务端，可选值: client, server

  loadBalance:
    type: consistenthash
  serialize:
    type: json
  server:
    port: 9000
    host: 127.0.0.1
    io-threads: 4
    worker-threads: 10
  registry:
    type: consul
    address: 127.0.0.1:8500
  ratelimit:
    enabled: false
    default:
      qps: 100

# 日志配置
logging:
  level:
    com.weihua.rpc: info
    root: warn

