server:
  port: 8081

spring:
  application:
    name: rpc-example-provider

# RPC 配置
rpc:
  mode: server  # 指定模式为服务端

  loadBalance:
    type: consistenthash
  serialize:
    type: json
  server:
    port: 9000
    host: 127.0.0.1
    io-threads: 4
    worker-threads: 10
    # 添加服务端心跳配置
    heartbeat:
      timeout: 15s               # 服务端心跳超时时间
      
  registry:
    type: consul
    address: 127.0.0.1:8500
    # 优化注册中心相关配置
    check-interval: 10s          # 健康检查间隔
    check-timeout: 5s            # 健康检查超时
    deregister-time: 30s         # 服务注销时间
    
  ratelimit:
    enabled: true
    default:
      qps: 100

# 日志配置
logging:
  level:
    com.weihua.rpc: info
    root: warn